/*  lrsutilfunc7.inc

    March 21, 2005

    SCIPS.com, Inc.

    Standard Functions items for SCIPS Version 7
*/

"util1"	display "lrsmt01e" 
			tagged reportable_claim_fn;

"util2"	display "apsmt204" 
			tagged transaction_code_fn;

"util3"	display "apsmt010" 
			tagged vendor_fn;

"util4"	display "apsmt011" 
			tagged reserve_default_fn;

"util5"	display "sfsmt237" 
			tagged cause_of_loss_fn;

"util6"	display "lrsmt01e" 
			tagged summary_trans_codes_fn;

"util7"	display "" 
			tagged view_print_dec_fn;
